### ISSUE TITLE
Please change your avatar in your profile

### ISSUE THREAD

**Issue by zxp86021** [carefreetime/FinalProject_Post#2]
As title

**Comment by x3388638** [comment]
![photo_2017-06-19_20-38-13](https://user-images.githubusercontent.com/8147952/27285445-5a527368-552f-11e7-8355-7079ee227c47.jpg)

**Comment by YuerLee** [comment]
![image](https://user-images.githubusercontent.com/2075566/27285519-9279207a-552f-11e7-9800-03ce9a4fb565.png)

Photo by @zxp86021

**Comment by x3388638** [comment]
棒棒

**Comment by carefreetime** [comment]
學長好兇
